<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
class SupplyTableSeeder extends Seeder {
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		App\Supply::truncate();
		App\Supply::insert([
		array( 'stocknumber' => '01-001','unit_id' => '6','reorderpoint'=> '0','details' => 'ACETATE, TRANSPARENT. 1.20 MTRS. MIN. WIDTH, 50meters/roll'),
		array( 'stocknumber' => '01-002','unit_id' => '3','reorderpoint'=> '0','details' => 'AIR FRESHNER '),
		array( 'stocknumber' => '01-003','unit_id' => '4','reorderpoint'=> '0','details' => 'ALCOHOL, RUBBING, 70%'),
		array( 'stocknumber' => '01-004','unit_id' => '2','reorderpoint'=> '0','details' => 'AUDIO CASSETTE TAPE, BLANK, 120 MIN'),
		array( 'stocknumber' => '01-005','unit_id' => '2','reorderpoint'=> '0','details' => 'AIRPOT, 4 LITERS '),
		array( 'stocknumber' => '02-001','unit_id' => '2','reorderpoint'=> '0','details' => 'BALLAST, 18/20/26 WATTS'),
		array( 'stocknumber' => '02-002','unit_id' => '2','reorderpoint'=> '0','details' => 'BALLAST, 36 WATTS'),
		array( 'stocknumber' => '02-003','unit_id' => '2','reorderpoint'=> '0','details' => 'BALLAST, 40 WATTS'),
		array( 'stocknumber' => '02-004','unit_id' => '2','reorderpoint'=> '0','details' => 'BALLPEN FINE POINT BLACK (12pcs./Box)'),
		array( 'stocknumber' => '02-005','unit_id' => '2','reorderpoint'=> '0','details' => 'BALLPEN FINE POINT BLUE '),
		array( 'stocknumber' => '02-006','unit_id' => '2','reorderpoint'=> '0','details' => 'BALLPEN FINE POINT RED'),
		array( 'stocknumber' => '02-007','unit_id' => '13','reorderpoint'=> '0','details' => 'BATTERY (AA) 2pcs/pack'),
		array( 'stocknumber' => '02-008','unit_id' => '13','reorderpoint'=> '0','details' => 'BATTERY (AAA) 2pcs/pack'),
		array( 'stocknumber' => '02-009','unit_id' => '2','reorderpoint'=> '0','details' => 'BINDER, TB, 11 x 14-7/8"'),
		array( 'stocknumber' => '02-010','unit_id' => '2','reorderpoint'=> '0','details' => 'BATTERY D, 1.5 BOLTS 2 PCS/PACK'),
		array( 'stocknumber' => '03-001','unit_id' => '2','reorderpoint'=> '0','details' => 'CALCULATOR, SCIENTIFIC, 10 + 2 DIGITS CAP. DOT MATRIX, TWO WAY(SOLAR/CELL TYPE) ADRITE BRAND'),
		array( 'stocknumber' => '03-002','unit_id' => '13','reorderpoint'=> '0','details' => 'CARBON PAPER, LONG, 100/BXS'),
		array( 'stocknumber' => '03-003','unit_id' => '2','reorderpoint'=> '0','details' => 'CARTOLINA, ASSORTED COLORS'),
		array( 'stocknumber' => '03-004','unit_id' => '7','reorderpoint'=> '0','details' => 'COMPUTER FORMS, 1 PLY, 11¼" x 8⅝" x 6½"'),
		array( 'stocknumber' => '03-005','unit_id' => '7','reorderpoint'=> '0','details' => 'CHALK WHITE DUSTLESS, DURA SMOOTH, 100/BXS '),
		array( 'stocknumber' => '03-006','unit_id' => '7','reorderpoint'=> '0','details' => 'CLIP PAPER, GEM TYPE 32MM (1¼"), VINYL COATED, 100/BOX RAINBOW'),
		array( 'stocknumber' => '03-007','unit_id' => '7','reorderpoint'=> '0','details' => 'CLIP PAPER, GEM TYPE 50MM (2"), VINYL COATED, 100/BOX RAINBOW'),
		array( 'stocknumber' => '03-008','unit_id' => '7','reorderpoint'=> '0','details' => 'CLIP, BACKFOLD, 19MM (¾") ALL METAL, 12PCS/BOX'),
		array( 'stocknumber' => '03-009','unit_id' => '7','reorderpoint'=> '0','details' => 'CLIP, BACKFOLD, 25MM (1") ALL METAL, 12PCS/BOX'),
		array( 'stocknumber' => '03-010','unit_id' => '2','reorderpoint'=> '0','details' => 'COLUMNAR 6 COLUMS                                                           '),
		array( 'stocknumber' => '03-011','unit_id' => '2','reorderpoint'=> '0','details' => 'COMPACT DISC. REWRITABLE (CD-RW) 700MB MINS CAP. 80MINS REC.'),
		array( 'stocknumber' => '03-012','unit_id' => '7','reorderpoint'=> '0','details' => 'COMPUTER FORMS, 1 PLY, PLAIN , 11" X 14.88"'),
		array( 'stocknumber' => '03-013','unit_id' => '7','reorderpoint'=> '0','details' => 'COMPUTER FORMS, 1 PLY, PLAIN , 11" X 14-7/8"'),
		array( 'stocknumber' => '03-014','unit_id' => '7','reorderpoint'=> '0','details' => 'COMPUTER FORMS, 1 PLY, PLAIN , 11" X 9-1/2"'),
		array( 'stocknumber' => '03-015','unit_id' => '7','reorderpoint'=> '0','details' => 'COMPUTER FORMS, 1 PLY, PLAIN , 3-2/3" X 8"'),
		array( 'stocknumber' => '03-016','unit_id' => '7','reorderpoint'=> '0','details' => 'COMPUTER FORMS, 2  PLY, PLAIN , 11" X 9-1/2"'),
		array( 'stocknumber' => '03-017','unit_id' => '7','reorderpoint'=> '0','details' => 'COMPUTER FORMS, 2 PLY, PLAIN , 11" X 14-7/8"'),
		array( 'stocknumber' => '03-018','unit_id' => '7','reorderpoint'=> '0','details' => 'COMPUTER FORMS, 3  PLY, PLAIN , 11" X 9-1/2"'),
		array( 'stocknumber' => '03-019','unit_id' => '2','reorderpoint'=> '0','details' => 'COMPUTER FORMS, 3 PLY, PLAIN , 11" X 14-7/8"'),
		array( 'stocknumber' => '03-020','unit_id' => '2','reorderpoint'=> '0','details' => 'CORRECTION FLUID WATER BASE 15 ML'),
		array( 'stocknumber' => '03-021','unit_id' => '2','reorderpoint'=> '0','details' => 'CORRECTION TAPE, DISPOSABLE, USABLE LENGTH OF 6MTRS. THICKNESS  '),
		array( 'stocknumber' => '03-022','unit_id' => '17','reorderpoint'=> '0','details' => 'CUTTER BLADE, HEAVY DUTY 18MM WIDTH, 10PCS/TUBE '),
		array( 'stocknumber' => '03-023','unit_id' => '2','reorderpoint'=> '0','details' => 'CUTTER, GEN. PURPOSE, HEAVY DUTY BUILT-IN W/ METAL SLIDING GUIDE W/ SCREW'),
		array( 'stocknumber' => '03-024','unit_id' => '2','reorderpoint'=> '0','details' => 'COMPACT FLOURESCENT LAMP (CFL) 18 watts '),
		array( 'stocknumber' => '03-025','unit_id' => '7','reorderpoint'=> '0','details' => 'CARBON, SHORT, 100/BXS'),
		array( 'stocknumber' => '03-026','unit_id' => '7','reorderpoint'=> '0','details' => 'CARBON PAPER, A4 SIZE, 100pcs./Box'),
		array( 'stocknumber' => '03-027','unit_id' => '7','reorderpoint'=> '0','details' => 'CLIP, BACKFOLD, 32MM(1 1/4)  ALL METAL, 12PCS/BOX'),
		array( 'stocknumber' => '03-028','unit_id' => '7','reorderpoint'=> '0','details' => 'CLIP, BACKFOLD, 50MM(2)  ALL METAL, 12PCS/BOX'),
		array( 'stocknumber' => '03-029','unit_id' => '2','reorderpoint'=> '0','details' => 'CALCULATOR, 12 DIGITS, TWO WAY POWER '),
		array( 'stocknumber' => '03-030','unit_id' => '2','reorderpoint'=> '0','details' => 'Calculator, Palm Size Printing, Canon'),
		array( 'stocknumber' => '03-031','unit_id' => '2','reorderpoint'=> '0','details' => 'CHAIR, monobloc, white, with backrest'),
		array( 'stocknumber' => '03-032','unit_id' => '7','reorderpoint'=> '0','details' => 'COMPUTER FORMS, 3 PLY, PLAIN , 11" X 17-⅞"'),
		array( 'stocknumber' => '04-001','unit_id' => '15','reorderpoint'=> '0','details' => 'N/A'),
		array( 'stocknumber' => '04-002','unit_id' => '2','reorderpoint'=> '0','details' => 'DVD, REWRITABLE '),
		array( 'stocknumber' => '04-003','unit_id' => '2','reorderpoint'=> '0','details' => 'DATA FOLDER, LONG '),
		array( 'stocknumber' => '04-004','unit_id' => '2','reorderpoint'=> '0','details' => 'DATING MACHINE, STAMP'),
		array( 'stocknumber' => '04-005','unit_id' => '2','reorderpoint'=> '0','details' => 'DRY SEAL, PUP SEAL'),
		array( 'stocknumber' => '04-006','unit_id' => '3','reorderpoint'=> '0','details' => 'DISINFECTANT SPRAY, KILLS OF GERMS & VIRUSES, 400G'),
		array( 'stocknumber' => '05-001','unit_id' => '2','reorderpoint'=> '0','details' => 'ENVELOPE DOCUMENTARY -GOLDEN KRAFT BROWN LONG 10 X 15'),
		array( 'stocknumber' => '05-002','unit_id' => '2','reorderpoint'=> '0','details' => 'ENVELOPE DOCUMENTARY SHORT 150 GSM 9 X 12'),
		array( 'stocknumber' => '05-003','unit_id' => '2','reorderpoint'=> '0','details' => 'ENVELOPE EXPANDING, LONG '),
		array( 'stocknumber' => '05-004','unit_id' => '2','reorderpoint'=> '0','details' => 'ENVELOPE EXPANDING, SHORT '),
		array( 'stocknumber' => '05-005','unit_id' => '2','reorderpoint'=> '0','details' => 'ENVELOPE, MAILING, WHITE 500/BX, SHORT'),
		array( 'stocknumber' => '05-006','unit_id' => '2','reorderpoint'=> '0','details' => 'ENVELOPE, MAILING, WHITE,  500/BX LONG '),
		array( 'stocknumber' => '05-007','unit_id' => '2','reorderpoint'=> '0','details' => 'ERASER, BLACKBOARD'),
		array( 'stocknumber' => '05-008','unit_id' => '2','reorderpoint'=> '0','details' => 'ERASER, RUBBER, RECTANGULAR, PLATON BRAND'),
		array( 'stocknumber' => '05-009','unit_id' => '2','reorderpoint'=> '0','details' => 'ENVELOPE, MAILING, WINDOW,  WHITE,  500/BX LONG '),
		array( 'stocknumber' => '05-010','unit_id' => '2','reorderpoint'=> '0','details' => 'N/A'),
		array( 'stocknumber' => '06-001','unit_id' => '7','reorderpoint'=> '0','details' => 'FACSIMILE INK FILM RECORDER NO. TTRP93 (2pcs./Box)'),
		array( 'stocknumber' => '06-002','unit_id' => '2','reorderpoint'=> '0','details' => 'FAN, ELECTRIC, ORBIT TYPE  18”diameter  '),
		array( 'stocknumber' => '06-003','unit_id' => '2','reorderpoint'=> '0','details' => 'FAN, ELECTRIC, with STAND TYPE'),
		array( 'stocknumber' => '06-004','unit_id' => '2','reorderpoint'=> '0','details' => 'FAN, ELECTRIC, TABLE/DESK/FLOOR TYPE '),
		array( 'stocknumber' => '06-005','unit_id' => '2','reorderpoint'=> '0','details' => 'FAN, ELECTRIC, WALL TYPE'),
		array( 'stocknumber' => '06-006','unit_id' => '7','reorderpoint'=> '0','details' => 'FANCY FOLDER SHORT'),
		array( 'stocknumber' => '06-007','unit_id' => '7','reorderpoint'=> '0','details' => 'FASTENER, METAL'),
		array( 'stocknumber' => '06-008','unit_id' => '7','reorderpoint'=> '0','details' => 'FASTENER, PLASTIC PRINCE'),
		array( 'stocknumber' => '06-009','unit_id' => '2','reorderpoint'=> '0','details' => 'FLASH DRIVE 16GB, USB VERSION 2.0 PORT COMPATIBLE, PLUG AND PLAY APACER BRAND'),
		array( 'stocknumber' => '06-010','unit_id' => '2','reorderpoint'=> '0','details' => 'FLASH DRIVE 8GB, USB VERSION 2.0 PORT COMPATIBLE, PLUG AND PLAY APACER BRAND'),
		array( 'stocknumber' => '06-011','unit_id' => '2','reorderpoint'=> '0','details' => 'FLOURESCENT LAMP TUBULAR 16 WATTS'),
		array( 'stocknumber' => '06-012','unit_id' => '2','reorderpoint'=> '0','details' => 'FLOURESCENT LAMP TUBULAR 18 WATTS '),
		array( 'stocknumber' => '06-013','unit_id' => '2','reorderpoint'=> '0','details' => 'FLOURESCENT LAMP TUBULAR 36 WATTS'),
		array( 'stocknumber' => '06-014','unit_id' => '2','reorderpoint'=> '0','details' => 'FLOURESCENT LAMP TUBULAR 40 WATTS'),
		array( 'stocknumber' => '06-015','unit_id' => '2','reorderpoint'=> '0','details' => 'FLOURESCENT LIGHTNING FIXTURE 1X40W'),
		array( 'stocknumber' => '06-016','unit_id' => '2','reorderpoint'=> '0','details' => 'FOLDER LONG TAG BOARD 14 POINTS LEGAL SIZE'),
		array( 'stocknumber' => '06-017','unit_id' => '2','reorderpoint'=> '0','details' => 'FOLDER SHORT TAG BOARD 14 POINTS LETTER SIZE                                    '),
		array( 'stocknumber' => '06-018','unit_id' => '2','reorderpoint'=> '0','details' => 'FLOURESCENT LAMP, 28WATTS 25/BOX'),
		array( 'stocknumber' => '06-019','unit_id' => '2','reorderpoint'=> '0','details' => 'FOLDER, PRESSBOARD , LEGAL PAPER BOARD.,100/PACK                     '),
		array( 'stocknumber' => '06-020','unit_id' => '2','reorderpoint'=> '0','details' => 'FOLDER, PRESSBOARD , SHORT PAPER BOARD.,100/PACK                     '),
		array( 'stocknumber' => '06-021','unit_id' => '2','reorderpoint'=> '0','details' => 'FOLDER, FANCY , LEGAL  SIZE PAPER DOC .,50/PACK                           '),
		array( 'stocknumber' => '06-022','unit_id' => '2','reorderpoint'=> '0','details' => 'FOLDER,  TAGBOARD, A4 SIZE DOC., 100/PACK                 '),
		array( 'stocknumber' => '06-023','unit_id' => '2','reorderpoint'=> '0','details' => 'FACSIMILE FILM (PANASONIC) KX-FP 342'),
		array( 'stocknumber' => '06-024','unit_id' => '2','reorderpoint'=> '0','details' => 'FLOURESCENT LAMP TUBULAR 20 WATTS'),
		array( 'stocknumber' => '06-025','unit_id' => '14','reorderpoint'=> '0','details' => 'FAN, ELECTRIC, ORBIT TYPE 16" diameter'),
		array( 'stocknumber' => '07-001','unit_id' => '4','reorderpoint'=> '0','details' => 'GLUE,  ALL PURPOSE IN JAR W/APPLICATOR 300 GRAMS'),
		array( 'stocknumber' => '08-001','unit_id' => '2','reorderpoint'=> '0','details' => 'HANDBOOK ON PHILIPPINE GOVT. PROCUREMENT '),
		array( 'stocknumber' => '08-002','unit_id' => '14','reorderpoint'=> '0','details' => 'HARD DRIVE, EXTERNAL, 1TB, 2.5mm HDD, 3.0 USB'),
		array( 'stocknumber' => '09-001','unit_id' => '7','reorderpoint'=> '0','details' => 'INDEX CARD BOX, 4-3/8x5-5/8" x 4"(3" x 5")'),
		array( 'stocknumber' => '09-002','unit_id' => '7','reorderpoint'=> '0','details' => 'INDEX CARD BOX, 5-3/8x8-7/8" x 6"(5" x 8")'),
		array( 'stocknumber' => '09-003','unit_id' => '7','reorderpoint'=> '0','details' => 'INDEX TAB, SELF-ADHESIVE '),
		array( 'stocknumber' => '09-004','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE FOR HP 840/845 #C6625A (HP 17)COLORED'),
		array( 'stocknumber' => '09-005','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE FOR HP 840C/845 #C6615A(HP 15) BLACK'),
		array( 'stocknumber' => '09-006','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE FOR HP 840C/845 #C6615A(HP 22 ) colored '),
		array( 'stocknumber' => '09-007','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE, HP21, BLACK '),
		array( 'stocknumber' => '09-008','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CART. FOR HP PRINTER, #1823, COLORED   HP23'),
		array( 'stocknumber' => '09-009','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE, HP27, BLACK'),
		array( 'stocknumber' => '09-010','unit_id' => '2','reorderpoint'=> '0','details' => 'INK HP LASERJET HP28, COLORED'),
		array( 'stocknumber' => '09-011','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE FOR HP 710C/830C #51645A BLACK HP 45'),
		array( 'stocknumber' => '09-012','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CART. FOR HP PRINTER 1220C C6578D ORIG. BRAND NEW COLORED HP78'),
		array( 'stocknumber' => '09-013','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE, BLACK  #38'),
		array( 'stocknumber' => '09-014','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE, COLORED  #39'),
		array( 'stocknumber' => '09-015','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE ,HP60 BLACK '),
		array( 'stocknumber' => '09-016','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE, HP60 COLORED'),
		array( 'stocknumber' => '09-017','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE HP96, BLACK'),
		array( 'stocknumber' => '09-018','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE  HP97, COLORED'),
		array( 'stocknumber' => '09-019','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET CARTRIDGE, HP #CD887AA (HP703)/D730/SERIES#736 BLACK'),
		array( 'stocknumber' => '09-020','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET CARTRIDGE, HP #CD888AA (HP703)/D730/SERIES#735 COLORED'),
		array( 'stocknumber' => '09-021','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE, HP900 COLORED '),
		array( 'stocknumber' => '09-022','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE,  HP900 BLACK'),
		array( 'stocknumber' => '09-023','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE HP18, BLACK'),
		array( 'stocknumber' => '09-024','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE  HP18, CYAN'),
		array( 'stocknumber' => '09-025','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE  HP18, YELLOW'),
		array( 'stocknumber' => '09-026','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE HP18, MAGENTA'),
		array( 'stocknumber' => '09-027','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE  HP #CD972AA (HP 920XL), CYAN '),
		array( 'stocknumber' => '09-028','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE  HP #CD973AA (HP 920XL), MAGENTA '),
		array( 'stocknumber' => '09-029','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE  HP #CD974AA (HP 920XL), YELLOW'),
		array( 'stocknumber' => '09-030','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET  CARTRIDGE  HP #CD975AA (HP 920XL), BLACK'),
		array( 'stocknumber' => '09-031','unit_id' => '2','reorderpoint'=> '0','details' => 'INK EPSON L110 (BLACK)'),
		array( 'stocknumber' => '09-032','unit_id' => '2','reorderpoint'=> '0','details' => 'INK EPSON L110 (CYAN)'),
		array( 'stocknumber' => '09-033','unit_id' => '2','reorderpoint'=> '0','details' => 'INK EPSON L110 (MAGENTA)'),
		array( 'stocknumber' => '09-034','unit_id' => '2','reorderpoint'=> '0','details' => 'INK EPSON L110 (YELLOW)'),
		array( 'stocknumber' => '09-035','unit_id' => '2','reorderpoint'=> '0','details' => 'INK COPYPRINTER, BLACK, GESTETNER MODEL 5307/5308/3440/5430, CPI 7'),
		array( 'stocknumber' => '09-036','unit_id' => '2','reorderpoint'=> '0','details' => 'INK COPYPRINTER, BLACK, GESTETNER MODEL 5329, CPI 2'),
		array( 'stocknumber' => '09-037','unit_id' => '2','reorderpoint'=> '0','details' => 'N/A'),
		array( 'stocknumber' => '09-038','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET CARTRIDGE, HP704, BLACK'),
		array( 'stocknumber' => '09-039','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET CARTRIDGE,HP704, COLORED'),
		array( 'stocknumber' => '09-040','unit_id' => '2','reorderpoint'=> '0','details' => 'INKJET CARTRIDGE, HP CC653 (901) BLACK, OFFICEJET 4580'),
		array( 'stocknumber' => '09-041','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, HP CC656AA, (901) TRI-COLOR OFFICEJET 4500'),
		array( 'stocknumber' => '09-042','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, OPSCAN 4U, 51604A'),
		array( 'stocknumber' => '09-043','unit_id' => '2','reorderpoint'=> '0','details' => 'INK DESKJET , CANNON FIXMA MX366 PG810 , BLACK'),
		array( 'stocknumber' => '09-044','unit_id' => '2','reorderpoint'=> '0','details' => 'INK DESKJET , CANNON FIXMA MX366 PG811 , COLORED'),
		array( 'stocknumber' => '09-045','unit_id' => '5','reorderpoint'=> '0','details' => 'INDEX CARD,3x 5",ruled both sides, 100s/bundle'),
		array( 'stocknumber' => '09-046','unit_id' => '5','reorderpoint'=> '0','details' => 'INDEX CARD, 5 x 8",ruled both side, 100s/bundle'),
		array( 'stocknumber' => '09-047','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CANON, 830, BLACK'),
		array( 'stocknumber' => '09-048','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CANON, 831, COLORED'),
		array( 'stocknumber' => '09-049','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, BLACK'),
		array( 'stocknumber' => '09-050','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, CYAN'),
		array( 'stocknumber' => '09-051','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, MAGENTA'),
		array( 'stocknumber' => '09-052','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, YELLOW'),
		array( 'stocknumber' => '09-053','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, HP98'),
		array( 'stocknumber' => '09-054','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CANNON, #40'),
		array( 'stocknumber' => '09-055','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CANNON, #41'),
		array( 'stocknumber' => '09-056','unit_id' => '4','reorderpoint'=> '0','details' => 'INK DUPLO DP514 '),
		array( 'stocknumber' => '09-057','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, GESTETNER DX2430, BLACK'),
		array( 'stocknumber' => '09-058','unit_id' => '3','reorderpoint'=> '0','details' => 'INSECTICIDE, MULTI INSECT KILLER, KILLS FLYING AND CRAWLING INSECTS'),
		array( 'stocknumber' => '09-059','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, HP 75, COLORED'),
		array( 'stocknumber' => '09-060','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, HP 74, BLACK'),
		array( 'stocknumber' => '09-061','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, MP C1500 black'),
		array( 'stocknumber' => '09-062','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, MP C1500 cyan'),
		array( 'stocknumber' => '09-063','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, MP C1500 yellow'),
		array( 'stocknumber' => '09-064','unit_id' => '11','reorderpoint'=> '0','details' => 'INK CARTRIDGE, MP C1500 Magenta'),
		array( 'stocknumber' => '09-065','unit_id' => '2','reorderpoint'=> '0','details' => 'INK JET HP 932, CL0575, BLACK '),
		array( 'stocknumber' => '09-066','unit_id' => '2','reorderpoint'=> '0','details' => 'INK JET HP 933, CN0585, CYAN '),
		array( 'stocknumber' => '09-067','unit_id' => '2','reorderpoint'=> '0','details' => 'INK JET HP 933, CN059S, MAGENTA'),
		array( 'stocknumber' => '09-068','unit_id' => '2','reorderpoint'=> '0','details' => 'INK JET HP 933, CL060S,YELLOW'),
		array( 'stocknumber' => '09-069','unit_id' => '2','reorderpoint'=> '0','details' => 'INK DESKJET, ADVANTAGE, HP 678, BLACK '),
		array( 'stocknumber' => '09-070','unit_id' => '2','reorderpoint'=> '0','details' => 'INK DESKJET, ADNVANTAGE, HP 678, COLORED '),
		array( 'stocknumber' => '09-071','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CART, HP CN045AA, (HP950XL), BLACK'),
		array( 'stocknumber' => '09-072','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CART, HP CN046AA, (HP951XL), CYAN'),
		array( 'stocknumber' => '09-073','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CART, HP CN047AA, (HP951XL), MAGENTA'),
		array( 'stocknumber' => '09-074','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CART, HP CN048AA, (HP951XL), YELLOW'),
		array( 'stocknumber' => '09-075','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, HP940XL'),
		array( 'stocknumber' => '09-076','unit_id' => '2','reorderpoint'=> '0','details' => 'INK CARTRIDGE, HP932, BLACK'),
		array( 'stocknumber' => '12-001','unit_id' => '13','reorderpoint'=> '0','details' => 'LOOSELEAF COVER W/ PAPER CLOTH STRAP, GREEN 8 1/2 X 14 (50pcs/Pack)'),
		array( 'stocknumber' => '12-002','unit_id' => '2','reorderpoint'=> '0','details' => 'L-TYPE PLASTIC FOLDER'),
		array( 'stocknumber' => '13-001','unit_id' => '2','reorderpoint'=> '0','details' => 'MAGAZINE FILE, LONG DBM'),
		array( 'stocknumber' => '13-002','unit_id' => '2','reorderpoint'=> '0','details' => 'MAGAZINE FILE, SHORT'),
		array( 'stocknumber' => '13-003','unit_id' => '2','reorderpoint'=> '0','details' => 'MARKER, HIGHLIGHTER ASSORTED, NON TOXIC SMELL'),
		array( 'stocknumber' => '13-004','unit_id' => '2','reorderpoint'=> '0','details' => 'MARKING PEN PERMANENT BLACK'),
		array( 'stocknumber' => '13-005','unit_id' => '2','reorderpoint'=> '0','details' => 'MARKING PEN PERMANENT BLUE'),
		array( 'stocknumber' => '13-006','unit_id' => '2','reorderpoint'=> '0','details' => 'MARKING PEN PERMANENT RED'),
		array( 'stocknumber' => '13-007','unit_id' => '2','reorderpoint'=> '0','details' => 'MARKING PEN WHITEBOARD, BLACK'),
		array( 'stocknumber' => '13-008','unit_id' => '2','reorderpoint'=> '0','details' => 'MARKING PEN WHITEBOARD, BLUE'),
		array( 'stocknumber' => '13-009','unit_id' => '2','reorderpoint'=> '0','details' => 'MARKING PEN WHITEBOARD, RED'),
		array( 'stocknumber' => '13-010','unit_id' => '2','reorderpoint'=> '0','details' => 'MASTER COPY PRINTER, CMPT 17 MODEL 5307/5308 GESTETNER '),
		array( 'stocknumber' => '13-011','unit_id' => '2','reorderpoint'=> '0','details' => 'MEDAL,GOLD (ORDINARY)'),
		array( 'stocknumber' => '13-012','unit_id' => '2','reorderpoint'=> '0','details' => 'MOUSE. OPTICAL, USB CONNECTION TYPE, 400 DPI, PLUG AND PLAY: GENIUS NETSCROLL BRAND '),
		array( 'stocknumber' => '13-013','unit_id' => '2','reorderpoint'=> '0','details' => 'MAGAZINE FILE, W/ COVER, (cartile w/ operable cover holds up to A4 and Legal)'),
		array( 'stocknumber' => '13-014','unit_id' => '2','reorderpoint'=> '0','details' => 'MEDAL, SIZE 4.5CM,  SILVER (HONOR STUDENT)'),
		array( 'stocknumber' => '13-015','unit_id' => '2','reorderpoint'=> '0','details' => 'MEDAL, SIZE 4.5CM,  BRONZE (HONOR STUDENT)'),
		array( 'stocknumber' => '13-016','unit_id' => '2','reorderpoint'=> '0','details' => 'MEDAL, SILVER (ORDINARY)'),
		array( 'stocknumber' => '13-017','unit_id' => '2','reorderpoint'=> '0','details' => 'MEDAL,BRONZE (ORDINARY)'),
		array( 'stocknumber' => '13-018','unit_id' => '2','reorderpoint'=> '0','details' => 'N/A'),
		array( 'stocknumber' => '13-019','unit_id' => '2','reorderpoint'=> '0','details' => 'MASTER COPY PRINTER, CMPT 9, GESTETNER '),
		array( 'stocknumber' => '13-020','unit_id' => '15','reorderpoint'=> '0','details' => 'N/A'),
		array( 'stocknumber' => '14-001','unit_id' => '2','reorderpoint'=> '0','details' => 'NOTEBOOK, STENOGRAPHIC, SPIRAL, 40 LEAVES'),
		array( 'stocknumber' => '14-002','unit_id' => '7','reorderpoint'=> '0','details' => 'NOTARIAL SEAL, NO. 24 SMALL BOX (40PCS./BOX)'),
		array( 'stocknumber' => '14-003','unit_id' => '9','reorderpoint'=> '0','details' => 'NOTE PAD, STICK-ON (2X3") 100 SHEETS PER PAD"'),
		array( 'stocknumber' => '14-004','unit_id' => '9','reorderpoint'=> '0','details' => 'NOTE PAD, STICK-ON (3X3") 100 SHEETS PER PAD"'),
		array( 'stocknumber' => '14-005','unit_id' => '9','reorderpoint'=> '0','details' => 'NOTE PAD, STICK-ON (3X4") 100 SHEETS PER PAD"'),
		array( 'stocknumber' => '16-001','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER BOND WHITE LONG, 70 GSM PG 8-1/2 X 13""'),
		array( 'stocknumber' => '16-002','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER BOND WHITE SHORT, SUBS. 20 GOOD QUALITY'),
		array( 'stocknumber' => '16-003','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER, MIMEO WHITE WOVE 70 GSM, LONG'),
		array( 'stocknumber' => '16-004','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER, MIMEO WHITE WOVE 70 GSM, SHORT'),
		array( 'stocknumber' => '16-005','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER, NEWSPRINT, PICOP LONG, 11x17'),
		array( 'stocknumber' => '16-006','unit_id' => '2','reorderpoint'=> '0','details' => 'PAPER, MANILA '),
		array( 'stocknumber' => '16-007','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER MIMEOGRAPH GROUNDWOOD, 216MM X 330MM, 60GSM'),
		array( 'stocknumber' => '16-008','unit_id' => '2','reorderpoint'=> '0','details' => 'PASTE, WATER WELL'),
		array( 'stocknumber' => '16-009','unit_id' => '2','reorderpoint'=> '0','details' => 'PENCIL LEAD W/ ERASER'),
		array( 'stocknumber' => '16-010','unit_id' => '2','reorderpoint'=> '0','details' => 'PENCIL SHARPENER'),
		array( 'stocknumber' => '16-011','unit_id' => '2','reorderpoint'=> '0','details' => 'PENCIL, MECHANICAL, 0.5 STEADLER (12pcs./box)'),
		array( 'stocknumber' => '16-012','unit_id' => '2','reorderpoint'=> '0','details' => 'PUNCHER'),
		array( 'stocknumber' => '16-013','unit_id' => '7','reorderpoint'=> '0','details' => 'PUSH PIN, FLAT HEAD TYPE , ASSORTED COLORS, 100PCS/CASE'),
		array( 'stocknumber' => '16-014','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER BOND WHITE SHORT, SUBS. A4 GOOD QUALITY'),
		array( 'stocknumber' => '16-015','unit_id' => '9','reorderpoint'=> '0','details' => 'PAPER, RULED PAD, 216MMX330, 90 SHEETS/PAD'),
		array( 'stocknumber' => '16-016','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER, MULTI-COLOURED, 8½" x 11" (250sheets/ream)'),
		array( 'stocknumber' => '16-017','unit_id' => '2','reorderpoint'=> '0','details' => 'Philippines Flag ,    3 ft x 6 ft. Standard'),
		array( 'stocknumber' => '16-018','unit_id' => '2','reorderpoint'=> '0','details' => 'Philippines Flag ,    Big Size'),
		array( 'stocknumber' => '16-019','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER, LAID, 8½" x 11" (500sheets/ream)'),
		array( 'stocknumber' => '16-020','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER, LAID, 8½" x 13" (500sheets/ream)'),
		array( 'stocknumber' => '16-021','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER BOND, WHITE, MULTI-COPY, 80GSM, 8½" x 11" (500sheets/Ream)'),
		array( 'stocknumber' => '16-022','unit_id' => '2','reorderpoint'=> '0','details' => 'PAPER BOND, 20 gsm.,  8½" x 11", YELLOW'),
		array( 'stocknumber' => '16-023','unit_id' => '2','reorderpoint'=> '0','details' => 'PAPER BOND, 20 gsm., 8½" x 11", MAGENTA'),
		array( 'stocknumber' => '16-024','unit_id' => '10','reorderpoint'=> '0','details' => 'PAPER, NEWSPRINT, 8½" x 11" (500sheet/ream)'),
		array( 'stocknumber' => '16-025','unit_id' => '13','reorderpoint'=> '0','details' => 'PARCHMENT PAPER, LEGAL SIZE (100pcs./Pack)'),
		array( 'stocknumber' => '18-001','unit_id' => '2','reorderpoint'=> '0','details' => 'RECORD BOOK , 300 PAGES'),
		array( 'stocknumber' => '18-002','unit_id' => '2','reorderpoint'=> '0','details' => 'RECORD BOOK , 500 PAGES'),
		array( 'stocknumber' => '18-003','unit_id' => '12','reorderpoint'=> '0','details' => 'RIBBON , MANUAL TYPEWRITER '),
		array( 'stocknumber' => '18-004','unit_id' => '2','reorderpoint'=> '0','details' => 'RIBBON FOR FAX  KX-FP701 (PANASONIC)'),
		array( 'stocknumber' => '18-005','unit_id' => '2','reorderpoint'=> '0','details' => 'RIBBON FOR PRINTER, EPSON LQ-2170/2180/2190 ORIGINAL (S015531)                             '),
		array( 'stocknumber' => '18-006','unit_id' => '15','reorderpoint'=> '0','details' => 'RIBBON CARTRIDGE, ERC-31B "Epson"'),
		array( 'stocknumber' => '18-007','unit_id' => '7','reorderpoint'=> '0','details' => 'RIBBON LX-300/800 PRINTER EPSON ORIGINAL'),
		array( 'stocknumber' => '18-008','unit_id' => '7','reorderpoint'=> '0','details' => 'RUBBER BAND'),
		array( 'stocknumber' => '18-009','unit_id' => '2','reorderpoint'=> '0','details' => 'RULER, 12"'),
		array( 'stocknumber' => '18-010','unit_id' => '2','reorderpoint'=> '0','details' => 'RULER, 18"'),
		array( 'stocknumber' => '18-011','unit_id' => '2','reorderpoint'=> '0','details' => 'RULER, 24"'),
		array( 'stocknumber' => '18-012','unit_id' => '13','reorderpoint'=> '0','details' => 'RING BINDER, 12.7mm x 1.12m (1/2"x 44"), plastic 10pcs/pack'),
		array( 'stocknumber' => '18-013','unit_id' => '13','reorderpoint'=> '0','details' => 'RING BINDER, 19mm x 1.12m(3/4"x 44"), plastic" 10pcs/pack'),
		array( 'stocknumber' => '18-014','unit_id' => '13','reorderpoint'=> '0','details' => 'RING BINDER, 25mm x 1.12m (1"x 44"), plastic" 10pcs/pack'),
		array( 'stocknumber' => '18-015','unit_id' => '13','reorderpoint'=> '0','details' => 'RING BINDER, 51mm x 1.12m(2" x 44"), plastic" 10pcs/pack'),
		array( 'stocknumber' => '18-016','unit_id' => '2','reorderpoint'=> '0','details' => 'RIBBON FACSIMILE PANASONIC KX-FP342CX '),
		array( 'stocknumber' => '18-017','unit_id' => '2','reorderpoint'=> '0','details' => 'REGISTRATION CARD'),
		array( 'stocknumber' => '18-018','unit_id' => '7','reorderpoint'=> '0','details' => 'RIBBON, YMCKO full color, 250 prints/roll'),
		array( 'stocknumber' => '18-019','unit_id' => '2','reorderpoint'=> '0','details' => 'RIBBON, EPSON FX 100 #8755'),
		array( 'stocknumber' => '19-001','unit_id' => '2','reorderpoint'=> '0','details' => 'SCISSORS, 158MM MIN. LENGTH, SYMMETRICAL, JOY BRAND'),
		array( 'stocknumber' => '19-002','unit_id' => '8','reorderpoint'=> '0','details' => ''),
		array( 'stocknumber' => '19-003','unit_id' => '2','reorderpoint'=> '0','details' => 'SIGNPEN, BLACK, LIQUID GEL INK, 0.5MM NEEDLE TIP, PENTEL ENERJEL BRAND'),
		array( 'stocknumber' => '19-004','unit_id' => '2','reorderpoint'=> '0','details' => 'SIGNPEN, BLUE, LIQUID GEL INK, 0.5MM NEEDLE TIP, PENTEL ENERJEL BRAND'),
		array( 'stocknumber' => '19-005','unit_id' => '2','reorderpoint'=> '0','details' => 'SIGNPEN, RED, LIQUID GEL INK, 0.5MM NEEDLE TIP, PENTEL ENERJEL BRAND'),
		array( 'stocknumber' => '19-006','unit_id' => '2','reorderpoint'=> '0','details' => 'STAMP PAD'),
		array( 'stocknumber' => '19-007','unit_id' => '4','reorderpoint'=> '0','details' => 'STAMP PAD, INK, 50ml'),
		array( 'stocknumber' => '19-008','unit_id' => '7','reorderpoint'=> '0','details' => 'STAPLE WIRE, Standard, No.35                                                               '),
		array( 'stocknumber' => '19-009','unit_id' => '2','reorderpoint'=> '0','details' => 'STAPLE WIRE, REMOVER'),
		array( 'stocknumber' => '19-010','unit_id' => '2','reorderpoint'=> '0','details' => 'STAPLER, HEAVY DUTY'),
		array( 'stocknumber' => '19-011','unit_id' => '2','reorderpoint'=> '0','details' => 'STARTER, 40W 25/BOX'),
		array( 'stocknumber' => '19-012','unit_id' => '15','reorderpoint'=> '0','details' => 'N/A'),
		array( 'stocknumber' => '19-013','unit_id' => '2','reorderpoint'=> '0','details' => 'STAPLER, BINDER TYPE HEAVY DUTY,  STAPLING, 12MM AND 17MM, CAP: 25-135 SHEETS OF 70GSM BOND PAPER'),
		array( 'stocknumber' => '19-014','unit_id' => '7','reorderpoint'=> '0','details' => 'STAPLE WIRE, 23/17, CHISEL POINTED (5/8")'),
		array( 'stocknumber' => '19-015','unit_id' => '2','reorderpoint'=> '0','details' => 'STAPLE WIRE, REMOVER PLIER TYPE'),
		array( 'stocknumber' => '20-001','unit_id' => '2','reorderpoint'=> '0','details' => 'TAPE DISPENCER, HEAVY DUTY 25MM (1) WIDTH TRANS. TAPE "'),
		array( 'stocknumber' => '20-002','unit_id' => '2','reorderpoint'=> '0','details' => 'TAPE MASKING 1", 24MM '),
		array( 'stocknumber' => '20-003','unit_id' => '2','reorderpoint'=> '0','details' => 'TAPE MASKING 2", 48MM '),
		array( 'stocknumber' => '20-004','unit_id' => '2','reorderpoint'=> '0','details' => 'TAPE, ADDING MACHINE  57M (2-1/4 WIDTH) 55GSM"'),
		array( 'stocknumber' => '20-005','unit_id' => '2','reorderpoint'=> '0','details' => 'TAPE, ELECRICAL'),
		array( 'stocknumber' => '20-006','unit_id' => '2','reorderpoint'=> '0','details' => 'TAPE, PACKAGING, 2"'),
		array( 'stocknumber' => '20-007','unit_id' => '2','reorderpoint'=> '0','details' => 'TAPE, TRANSPARENT, 1"  24 MM ARMAK BRAND'),
		array( 'stocknumber' => '20-008','unit_id' => '2','reorderpoint'=> '0','details' => 'TAPE, TRANSPARENT, 2  24 MM ARMAK BRAND "'),
		array( 'stocknumber' => '20-009','unit_id' => '7','reorderpoint'=> '0','details' => 'THUMBTACK'),
		array( 'stocknumber' => '20-010','unit_id' => '2','reorderpoint'=> '0','details' => 'TOILET, TISSUE PAPER, 2PLY SHEET/12RLS /PACK'),
		array( 'stocknumber' => '20-011','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP 05A , CE505A'),
		array( 'stocknumber' => '20-012','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP KONICA MINOLTA, BISHUB 210 (TN-114)'),
		array( 'stocknumber' => '20-013','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP P3010 (HP55A)'),
		array( 'stocknumber' => '20-014','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP OFFICEJET 7000'),
		array( 'stocknumber' => '20-015','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRDGE, HP LASER JET 1100/1100A C4092A BLACK'),
		array( 'stocknumber' => '20-016','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRDGE, HP LASER JET 85A (CE285AC) (P1102)'),
		array( 'stocknumber' => '20-017','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP LASER JET 1200 C7115A BLACK'),
		array( 'stocknumber' => '20-018','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP LASER JET 1300/13A'),
		array( 'stocknumber' => '20-019','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP LASER JET 5/6L C3906A/F BLACK'),
		array( 'stocknumber' => '20-020','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP LASER JET 53A  BLACK'),
		array( 'stocknumber' => '20-021','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP C9730A, black   '),
		array( 'stocknumber' => '20-022','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP C9731A, cyan   '),
		array( 'stocknumber' => '20-023','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP C9732A, yellow  '),
		array( 'stocknumber' => '20-024','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP C9733A, magenta  '),
		array( 'stocknumber' => '20-025','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP CB540A, black   HP125'),
		array( 'stocknumber' => '20-026','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP CB541A, cyan  HP125'),
		array( 'stocknumber' => '20-027','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP CB542A, yellow  HP125'),
		array( 'stocknumber' => '20-028','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP CB543A, magenta HP125'),
		array( 'stocknumber' => '20-029','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER FOR  KYOCERA  KM-1620 (TK-410)'),
		array( 'stocknumber' => '20-030','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER FOR  KYOCERA MITA, MODEL KM-2820 (TK-135)'),
		array( 'stocknumber' => '20-031','unit_id' => '15','reorderpoint'=> '0','details' => 'N/A'),
		array( 'stocknumber' => '20-032','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER FOR KYOCERA 220 (TK-439)'),
		array( 'stocknumber' => '20-033','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER FOR KYOCERA LASER PRINTER MODEL FS-1030D (TK-120)'),
		array( 'stocknumber' => '20-034','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER FOR KYOCERA LASER PRINTER MODEL FS-820/920(TK-110) '),
		array( 'stocknumber' => '20-035','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER FOR KYOCERA MITA DIGITAL COPIER MODEL KM-2530/3035, TONER A'),
		array( 'stocknumber' => '20-036','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER FOR KYOCERA MITA, MODEL KM-1820 (TK-100)'),
		array( 'stocknumber' => '20-037','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER FOR KYOCERA, KM-2030'),
		array( 'stocknumber' => '20-038','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER GESTETNER, KONICA TN 101/KN 118'),
		array( 'stocknumber' => '20-039','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER HP LASERJET PRINT CARTRIDGE 3050/Q2612AC'),
		array( 'stocknumber' => '20-040','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER HP LASERJET PRINT CARTRIDGE 35A'),
		array( 'stocknumber' => '20-041','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER GESTETNER DSM615/DSM618D (885474), 1500'),
		array( 'stocknumber' => '20-042','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER, KYOCERA TK70 9100/9500 SERIES 3050'),
		array( 'stocknumber' => '20-043','unit_id' => '15','reorderpoint'=> '0','details' => 'N/A'),
		array( 'stocknumber' => '20-044','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER, BROTHER DCP,  DN 7065 DR 225'),
		array( 'stocknumber' => '20-045','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER, CARTRIDGE HP #C8543 (9040DN), BLACK'),
		array( 'stocknumber' => '20-046','unit_id' => '2','reorderpoint'=> '0','details' => 'TAPE, PACKAGING, 2"'),
		array( 'stocknumber' => '20-047','unit_id' => '16','reorderpoint'=> '0','details' => 'TWINE, PLASTIC, ONE KL. PER ROLL'),
		array( 'stocknumber' => '20-048','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER, KYOCERA TK-1147'),
		array( 'stocknumber' => '20-049','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER, COPIER KYOCERA FS-6525MFP  TK-479'),
		array( 'stocknumber' => '20-050','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER, SHARP COPIER MACHINE AR-5520N, AR-021FT'),
		array( 'stocknumber' => '20-051','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER, CART. HP 127FN, HP83A'),
		array( 'stocknumber' => '20-052','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER, CARTIDGE MX-312FT, SHARP COPIER AR-5726'),
		array( 'stocknumber' => '20-053','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-23FTBA, BLACK'),
		array( 'stocknumber' => '20-054','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-23FTCA, CYAN'),
		array( 'stocknumber' => '20-055','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-23FTMA, MAGENTA'),
		array( 'stocknumber' => '20-056','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-23FTYA, YELLOW '),
		array( 'stocknumber' => '20-057','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER, KYOCERA ECOSYS FS-1040, TK-1114'),
		array( 'stocknumber' => '20-058','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-45FTBA, BLACK'),
		array( 'stocknumber' => '20-059','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-27FTCA, CYAN'),
		array( 'stocknumber' => '20-060','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-27FTMA, MAGENTA'),
		array( 'stocknumber' => '20-061','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-27FTYA, YELLOW '),
		array( 'stocknumber' => '20-062','unit_id' => '2','reorderpoint'=> '0','details' => 'TONER, SHARP COPIER MACHINE AR-016 FT'),
		array( 'stocknumber' => '20-063','unit_id' => '15','reorderpoint'=> '0','details' => 'N/A'),
		array( 'stocknumber' => '20-064','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-238FTI-3A, MODEL AR-6023N, BLACK'),
		array( 'stocknumber' => '20-065','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, SAMSUNG CLP-Y 406S, Black'),
		array( 'stocknumber' => '20-066','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, SAMSUNG CLP-Y 406S, Cyan'),
		array( 'stocknumber' => '20-067','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, SAMSUNG CLP-Y 406S, Magenta'),
		array( 'stocknumber' => '20-068','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, SAMSUNG CLP-Y 406S, Yellow '),
		array( 'stocknumber' => '20-069','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, HP 124A, BLACK'),
		array( 'stocknumber' => '20-070','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, KYOCERA, 1505/1510/1810'),
		array( 'stocknumber' => '20-071','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX 312 FT'),
		array( 'stocknumber' => '20-072','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-62FTBA, BLACK'),
		array( 'stocknumber' => '20-073','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-62FTCA, CYAN'),
		array( 'stocknumber' => '20-074','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-62FTYA, YELLOW'),
		array( 'stocknumber' => '20-075','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-62FTMA, MAGENTA'),
		array( 'stocknumber' => '20-076','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, MX-237FT'),
		array( 'stocknumber' => '20-077','unit_id' => '11','reorderpoint'=> '0','details' => 'TONER CARTRIDGE, LASERJET SAMSUNG 111S, EXPRESS M2020/2022/2070W'),
		array( 'stocknumber' => '20-078','unit_id' => '11','reorderpoint'=> '0','details' => 'Toner Cartridge Brother TN 3030'),
		array( 'stocknumber' => '20-079','unit_id' => '11','reorderpoint'=> '0','details' => 'Toner Cartridge Brother TN 3060'),
		array( 'stocknumber' => '21-001','unit_id' => '7','reorderpoint'=> '0','details' => 'ULTRACARD PLAIN PVC, CR-79/CR-80, 500 PCS/BOX '),
		array( 'stocknumber' => '23-001','unit_id' => '2','reorderpoint'=> '0','details' => 'WASTE BASKET, NON-RIGID PLASTIC, SQUARE, OVAL OR ROUND SHAPE, ASSORTED COLORS '),
		array( 'stocknumber' => '23-002','unit_id' => '5','reorderpoint'=> '0','details' => 'WRAPPING PAPER, KRAFT, 65gsm., 36" x 48" (100SHEETS/BUNDLE)'),
		]);
	}
}
